@extends('layout')
@section('title',$title)
@section('content')
<?=view('cat',['listtin'=>$listtin,'TenLT'=>$TenLT]);?>
@stop
@section('sidebar')
<?=view('tinxemnhieu',['lang'=>$lang]);?>
<?=view('loaitin',['lang'=>$lang]);?>
<?=view('banxemchua',['lang'=>$lang]);?>
@stop